[model]
mode = test1
msp = cpt

[data]
win_size = 320
input_c = 51
output_c = 51
data_name = SWaT
data_path = dataset/SWaT

[train]
lr = 0.0001
gpu = 0
epoch = 100
ar = 2.
bs = 512
seed = 0

[param]
d_model = 64
num_patch = 4,8
num_patches_tf = 4,8
e_layers = 3
dropout = 0.1
alpha = 1.0
beta = 1.0
gamma = 1.0

st_mask_ratio = 0.75
tf_mask_ratio = 0.5

mc_samples = 16
mc_mask_ratio_time = 1.
mc_mask_ratio_freq = 1.